repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-operator
    version: 82.4.3
    atomic: true
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    values:
      - values.yaml
