repositories:
  - name: bjw-s
    url: https://bjw-s-labs.github.io/helm-charts

releases:
  - name: scraparr
    version: 4.6.2
    atomic: true
    namespace: monitoring
    chart: bjw-s/app-template
    values:
      - values.yaml
