repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts

releases:
  - name: reloader
    version: 2.2.8
    atomic: true
    namespace: kube-system
    chart: stakater/reloader
    values:
      - values.yaml
