repositories:
  - name: rancher-latest
    url: https://releases.rancher.com/server-charts/latest

releases:
  - name: rancher
    version: 2.13.3
    atomic: true
    namespace: cattle-system
    chart: rancher-latest/rancher
    values:
      - values.yaml
